<?php
/**
* Data file generated by EMBFileMenu (ArrayModel)
* Date: July 30, 2013, 12:34 pm
*
* Allowed data structure:
*   array(
*       'menuid' => 'menuid',
*       'titles' => 'titles',
*       'descriptions' => 'descriptions',
*       'descriptionashint' => 'descriptionashint',
*       'visible' => 'visible',
*       'locked' => 'locked',
*       'sortposition' => 'sortposition',
*       'maxdepth' => 'maxdepth',
*       'icon' => 'icon',
*       'nestedconfig' => 'nestedconfig',
*       'userroles' => 'userroles',
*       'scenarios' => 'scenarios',
*       'adminroles' => 'adminroles',
*       'created' => 'created',
*       'createduser' => 'createduser',
*       'modified' => 'modified',
*       'modifieduser' => 'modifieduser',
*   )
*/
return array(
	0 => array(
		'menuid' => 'main',
		'titles' => array(
			'en_us' => 'Main menu',
			'de' => 'Hauptmen',
		),
		'descriptions' => array(
			'en_us' => '',
		),
		'descriptionashint' => true,
		'visible' => true,
		'locked' => false,
		'sortposition' => 0,
		'maxdepth' => 3,
		'icon' => '',
		'nestedconfig' => '[{"id":"643f20d96ec76f8804177d4e74a9414d"},{"id":"abd4713a9f0b1272f657bde201c731c5"}]',
		'userroles' => '',
		'scenarios' => '',
		'adminroles' => '',
		'created' => 'Jul 30, 2013 12:29:30 PM',
		'createduser' => '5',
		'modified' => 'Jul 30, 2013 12:34:02 PM',
		'modifieduser' => '5',
	),
	1 => array(
		'menuid' => 'sidebar_left',
		'titles' => array(
			'en_us' => 'Sidebar left',
			'de' => 'Seitenleiste links',
		),
		'descriptions' => array(
			'en_us' => '',
		),
		'descriptionashint' => true,
		'visible' => true,
		'locked' => false,
		'sortposition' => 0,
		'maxdepth' => 2,
		'icon' => '',
		'userroles' => '',
		'scenarios' => '',
		'adminroles' => '',
		'created' => 'Jul 30, 2013 12:29:31 PM',
		'createduser' => '5',
	),
);
